---
title: "Alignment AA"
author: "Paulyna Magana"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_width: 6
    fig_height: 4
    fig_caption: true
header-includes:
- \usepackage{gb4e}
- \noautomath

always_allow_html: true

knit: (function(input_file, encoding) { output_dir = "./PDFs_outcome";
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), output_dir, 'Gene_expression_Atlas.pdf'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Gene Expression

## Dependencies
```{r, message=FALSE}
library(ggplot2)
library(readr)
library(devtools)
library(rmarkdown)
```


## Import data

```{r, message=FALSE}
Transporters <-read_csv("data/ExpressionRMA.csv")
paged_table(Transporters)
```


# Create plot

```{r, fig.width=8, fig.height=12, message=FALSE}
gtrans <- ggplot(Transporters, aes(Transporter, Tissue, fill= Average_RMA)) + 
  geom_tile() +
  scale_fill_gradient(low="white", high="black") +
  theme(strip.placement = "outside",
        plot.title = element_text(hjust = 0.5)) +
  ggtitle(label = "SLC22 Abundance expression in human") +
  scale_y_discrete(limits = rev(levels(as.factor(Transporters$Tissue)))) +
  theme_classic()
#print
print(gtrans)
```

# Improve plot

```{r, fig.width=8, fig.height=10, message=FALSE}
#display axis names and rotate x label to a 90 angle
gtrans+labs(x ="Transporter", y = "Tissue/Cell Line") + theme(axis.text.x = element_text(angle=90)) 
```


# Session info
```{r session_info, comment=NA}
session_info()
```

